export const FETCH_EPISODES_BEGIN   = 'FETCH_EPISODES_BEGIN';
export const FETCH_EPISODES_SUCCESS = 'FETCH_EPISODES_SUCCESS';
export const FETCH_EPISODES_FAILURE = 'FETCH_EPISODES_FAILURE';

export const SELECT_EPISODES_BEGIN   = 'SELECT_EPISODES_BEGIN';
export const SELECT_EPISODES_SUCCESS = 'SELECT_EPISODES_SUCCESS';
export const SELECT_EPISODES_FAILURE = 'SELECT_EPISODES_FAILURE';

export const FETCH_SHOW_BEGIN = 'FETCH_SHOW_BEGIN'
export const FETCH_SHOW_SUCCESS = 'FETCH_SHOW_SUCCESS';
export const FETCH_SHOW_FAILURE = 'FETCH_SHOW_FAILURE';
