export const FETCH_EPISODES_BEGIN   = 'FETCH_EPISODES_BEGIN';
export const FETCH_EPISODES_SUCCESS = 'FETCH_EPISODES_SUCCESS';
export const FETCH_EPISODES_FAILURE = 'FETCH_EPISODES_FAILURE';

export const SHOW_SELECTED = 'SHOW_SELECTED';
export const NO_SHOW_SELECTED = 'NO_SHOW_SELECTED';
