export const FETCH_EPISODES_BEGIN   = 'FETCH_EPISODES_BEGIN';
export const FETCH_EPISODES_SUCCESS = 'FETCH_EPISODES_SUCCESS';
export const FETCH_EPISODES_FAILURE = 'FETCH_EPISODES_FAILURE';

export const FETCH_SHOW_BEGIN = 'FETCH_SHOW_BEGIN'
export const FETCH_SHOW_SUCCESS = 'FETCH_SHOW_SUCCESS';
export const FETCH_SHOW_FAILURE = 'FETCH_SHOW_FAILURE';

export const ADD_TO_FAVSHOWS = 'ADD_TO_FAVSHOWS';
export const REMOVE_FROM_FAVSHOWS = 'REMOVE_FROM_FAVSHOWS';
export const CLEAR_FAVSHOWS = 'CLEAR_FAVSHOWS';
